### ISSUE TITLE
Support PDF Creation 

### ISSUE THREAD

**Issue by Charliemowood** [redhataccess/ascii_binder#108]
It is a common a use case, to want transform your docs site into a PDF. It would a really nice feature to have as a command line tool. AsciiDoctor has for example https://github.com/asciidoctor/asciidoctor-pdf. Are there any plans to implement this feature?

**Comment by nhr** [comment]
I had a working branch with this in concept before I did the recent major refactor. I agree that it would be good to have a way to do single-file distribution of a docs set - be it PDF, ePub, or whatever.

**Comment by bexelbie** [comment]
@nhr can you share your idea here so we can consider possible implementations?

**Comment by nhr** [comment]
Currently, AsciiBinder processes each .adoc file in turn, by putting it into it's own HTML template with a  navigation component that is common to every page. In order to combine each .adoc file into a single volume, we will need to add each to a single in-memory file as we go.

The in-memory file (actually, just a very, very long string) can be built one of two ways:

1. "megafile" approach: Concatenate all of topic file together, but replace the top matter in each topic with a header for that topic (and an anchor that the navigation tree can reference).

2. "includefile" approach: Set up the in-memory file as a set of pointers to each topic per AsciiDoctor's instructions on [large-document partitioning](http://asciidoctor.org/docs/user-manual/#include-partitioning).

So that's the first part and openly I prefer approach #2.

Now that you have an includefile or megafile in memory, you need to transform it to PDF. AsciiDoctor can do this (see [AsciiDoctor PDF](http://asciidoctor.org/docs/asciidoctor-pdf/)), and it would be relatively easy to add the AsciiDoctor PDF gem requirements to our .gemspec file. However, this is also another step towards "AsciiDoctor lock-in", so I'm open to alternative approaches.

If we _did_ pursue the AsciiBinder PDF approach, then there is a lot of information in the docs to inform the way we need to construct the top matter in our includefile or megafile (see [An Example AsciiDoc Document](http://asciidoctor.org/docs/asciidoctor-pdf/#an-example-asciidoc-document)).

The most important thing to get right with a PDF version of a docs set is the TOC. Most PDF readers enable you to toggle the visibility of a TOC in the same way that the stock AsciiBinder templates include Nav on the left side of the page. AsciiDoctor PDF generates a TOC based on the header levels within the document, so some experimentation with level offsets should produce the right result. If we pursue any other approach, it will likely be on us to generate a TOC, which could be done by inspecting the contents of the TopicMap object's `nav_tree` method.

After all of that, the rest is relatively simple - the generated PDF needs to be dropped into a logical place in the `_preview` and `_package` directories by the `build` and `package` commands, respectively. We will probably want to also add a flag to these commands enabling a user to include or skip the PDF generation.
