### ISSUE TITLE
How to set user log level

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#115]
In the latest version you have added logging properties to the tool. I very much appreciate that step but now my outputs are less detailed. There is a message that I should set the log level to "debug" but I fail to see how I do that. I can find the place in the source code where the level is defined but I do not understand how to pass this to asciibinder at runtime. Is there a configuration file somewhere I can use instead?

**Comment by nhr** [comment]
The `asciibinder` command has ben updated, and a `-l` / `--log_level` argument is now available for most subcommands. For instance, you can run:

`asciibinder package -l debug` to see a complete dump of all messages.

Related: I think there is a bug in the way I count missing files, because I am not accounting for the fact that AsciiBinder allows topic map entries without the `.adoc` extension. I will fix that in my next PR.

**Comment by r0ckarong** [comment]
Which version will include this change? I'm currently getting 0.1.13 from NPM and this doesn't support this command.

**Comment by nhr** [comment]
Are you sure you have the right version? Here is what I am seeing:

```
$ asciibinder package -h
Usage:
  /usr/local/bin/asciibinder package <options> <docs_basedir>

Description:
  Publish mode is similar to 'build' mode, but once all of the branches' of
  HTML are generated, 'publish' goes on to organize the branch / distro
  combinations that are described in _distro_config.yml into their "site"
  layouts. As a final step, the site layouts are tarred and gzipped for
  easy placement onto a production web server.

Options:
  -s, --site=<s>         Instead of packaging every docs site, package the specified site only. (Default: )
  -l, --log-level=<s>    Set the logging output level for this operation. (Default: warn)
  -h, --help             Show this message
```

**Comment by nhr** [comment]
And that is for version 0.1.13

**Comment by r0ckarong** [comment]
Weird, after a reboot I'm seeing this now too. Nevermind then.
