### ISSUE TITLE
Support Distros glob matching

### ISSUE THREAD

**Issue by aweiteka** [redhataccess/ascii_binder#20]
I would like to have support for syntax like `Distros: <major_product>*` in the `_build_cfg.yml`. This would allow me to include major product families using shorter syntax instead of including a huge list of distros just to exclude another product family.

**Comment by nhr** [comment]
Just as a comment for my own reference: glob handling at the topic and topic group levels is easy because that behavior lives expressly within AsciiBinder. The `ifdef`/`endif` logic is trickier because those are being processed directly by AsciiDoctor. So in order to do this I will need to expand the globs in place immediately after reading the adoc file into memory [here](https://github.com/redhataccess/ascii_binder/blob/master/lib/ascii_binder/helpers.rb#L643).

**Comment by nhr** [comment]
I need to update the AsciiBinder docs but you can start using this feature by upgrading AsciiBinder to version 0.1.1.
