### ISSUE TITLE
Dockerfile does not build ascii_binder

### ISSUE THREAD

**Issue by jorgemoralespou** [redhataccess/ascii_binder#46]
It seems that listen requires a greater dependency than what is provided by SCL.

´´´´
[vagrant@origin asciibinder]$ docker build -t "asciibinder" .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM centos/ruby-22-centos7
Trying to pull repository docker.io/centos/ruby-22-centos7 ... latest: Pulling from centos/ruby-22-centos7
ed98430befc7: Pull complete
35da6faa16cc: Pull complete
29801532e4fd: Pull complete
f7747a5b1ac6: Pull complete
501ce8c368f7: Pull complete
ebe7f1777e28: Pull complete
458beeb57d87: Pull complete
1789b95af6fb: Pull complete
6b9bdf0afc86: Pull complete
20ec015bfd7c: Pull complete
7b999fdecff9: Pull complete
a85af1e6c1cd: Pull complete
01fc9f79d969: Pull complete
df3fd90b7887: Pull complete
8891572fb52c: Pull complete
195218537ee7: Pull complete
8423591d6c32: Pull complete
208484766f24: Pull complete
41894ab76b91: Pull complete
acc2590dcc90: Pull complete
917224853ffe: Pull complete
0626e5e46eb4: Pull complete
Digest: sha256:f60a507a26420e3889cee6cf43a9db375d58e42b1d0ba4beca9612772074559f
Status: Downloaded newer image for docker.io/centos/ruby-22-centos7:latest

 ---> 0626e5e46eb4
Step 2 : RUN scl enable rh-ruby22 -- gem install ascii_binder
 ---> Running in e502a52df126
Successfully installed asciidoctor-1.5.4
Successfully installed asciidoctor-diagram-1.4.0
Successfully installed git-1.3.0
Successfully installed formatador-0.2.5
Successfully installed rb-fsevent-0.9.7
Building native extensions.  This could take a while...
ERROR:  Error installing ascii_binder:
	listen requires Ruby version >= 2.2.3, ~> 2.2.
Successfully installed ffi-1.9.10
Successfully installed rb-inotify-0.9.7
Successfully installed ruby_dep-1.3.1
The command '/bin/sh -c scl enable rh-ruby22 -- gem install ascii_binder' returned a non-zero code: 1
´´´´

**Comment by nhr** [comment]
This is an annoying case introduced by the fact that many Ruby gemspecs describe a lower bound for version compatibility but not an upper bound. Normally not a problem if you are always using the latest Ruby, but since the docker image uses SCL, here we are.

Ideally this would be managed in gemspecs by tightening the version requirement for 'listen', but it is used by a handful of gems with varying version requirements, outside of the scope of the AsciiBinder gem.

By explicity installing a ruby22-friendly version of listen before anything else, we satisfy other gem dependencies with something that will work in the Docker environment.

**Comment by jorgemoralespou** [comment]
@nhr How can this be done?
"By explicity installing a ruby22-friendly version of listen before anything else, we satisfy other gem dependencies with something that will work in the Docker environment."

I want to to an asciibinder-s2i (https://github.com/jorgemoralespou/asciibinder-lighttpd-s2i) but failing due to this and my lack of knowledge on ruby and scl.

**Comment by nhr** [comment]
I've done it in this PR: https://github.com/redhataccess/ascii_binder/pull/47 - it needs to be reviewed.

**Comment by nhr** [comment]
Fix is merged.
