### ISSUE TITLE
Need link validator

### ISSUE THREAD

**Issue by adellape** [redhataccess/ascii_binder#7]
We need a way to validate links, at the very least for catching normal link typos during a local build. This could be either in `asciibinder` itself, or maybe implemented in `asciidoctor` upstream?

Also, currently whenever a topic changes location, the writer must manually search and update any affected links. It would be nice if `asciibinder` had a way to "move" a topic for you, such that it also just updated any links automatically.

**Comment by nhr** [comment]
This looks like an interesting possibility: https://github.com/gjtorikian/html-proofer
It would have to be run on the HTML output, and then the errors would need to be reconciled back to the original .adoc files...

**Comment by tpoitras** [comment]
Hey @nhr 

We still definitely need a way to validate links. Having to check everything manually any time a file is moved or removed is error-prone, and if our doc build hits the portal with a broken link, it halts the operation.

**Comment by rsmeral** [comment]
Link checking is definitely a must before publishing. However, does that fit within the purpose and model of asciibinder? Shouldn't asciibinder try to follow the "one thing well" paradigm? There even already is a documentation testing framework (including a link checker) developed in-house: https://github.com/emender/emender

**Comment by tpoitras** [comment]
I cannot speak to the purpose and model of asciibinder. Also, any links that I add manually are definitely checked before publishing. The problem comes in when a much-linked-to file is moved from one guide to another, thus breaking any links to that file. And if the file has a name which is not unique, it requires a tedious amount of grepping to find and fix all the broken links.

What I'm suggesting is that the build mechanism validates xrefs, and if it finds one that doesn't connect to  anything, the build would halt or fail and point to the broken link. I'm not a developer so I don't know if this is a small or large amount of coding to implement.

**Comment by rsmeral** [comment]
@tpoitras Sure, I understand why it's important and how it's painful to track the move (or rename - it's technically the same) manually.
If a file move is done in a separate commit, without any other changes to the file, then it's perfectly trackable using git. 

For example, there's `rugged`, a ruby library for handling git operations, which can detect file moves, see e.g. https://github.com/libgit2/rugged#diffs

```ruby
diff.find_similar!
diff.each_delta{ |d| puts d.inspect }
#<Rugged::Diff::Delta:70144372230920 {old_file: {:oid=>"81b68f040b120c9627518213f7fc317d1ed18e1c", :path=>"txt1", :size=>14, :flags=>6, :mode=>33188}, new_file: {:oid=>"81b68f040b120c9627518213f7fc317d1ed18e1c", :path=>"foo1", :size=>14, :flags=>6, :mode=>33188}, similarity: 100, status: :renamed>
#<Rugged::Diff::Delta:70144372230140 {old_file: {:oid=>"a7bb42f71183c162efea5e4c80597437d716c62b", :path=>"txt2", :size=>17, :flags=>6, :mode=>33188}, new_file: {:oid=>"a357de7d870823acc3953f1b2471f9c18d0d56ea", :path=>"txt2", :size=>29, :flags=>6, :mode=>33188}, similarity: 0, status: :modified>
```

asciibinder could walk all deltas since a given ref (e.g. a tag of the last release or publish event), and perform move detection on each one (see the `status: :renamed` property on a delta which is a move and not just a modification). If it found one, it could either warn about the move, or even do a search and replace on all occurrences of a link to that moved file.

**Comment by tnguyen-rh** [comment]
@nhr 
Perhaps https://github.com/redhataccess/ascii_binder/issues/28 can form the basis for link validation?
